INSERT INTO `voo` VALUES 
(1,'São Paulo, GRU - Brasil','Rio Branco, RBR - Brasil'),
(2,'São Paulo, GRU - Brasil','Maceió, MCZ - Brasil'),
(3,'São Paulo, GRU - Brasil','Manaus, MAO - Brasil'),
(4,'São Paulo, GRU - Brasil','Salvador da Bahia, SSA - Brasil'),
(5,'São Paulo, GRU - Brasil','Fortaleza, FOR - Brasil'),
(6,'São Paulo, GRU - Brasil','Brasília, BSB - Brasil'),
(7,'São Paulo, GRU - Brasil','Vitória, VIX - Brasil'),
(8,'São Paulo, GRU - Brasil','Goiânia, GYN - Brasil'),
(9,'São Paulo, GRU - Brasil','São Luís, SLZ - Brasil'),
(10,'São Paulo, GRU - Brasil','Cuiabá, CGB - Brasil'),
(11,'São Paulo, GRU - Brasil','Campo Grande, CGR - Brasil'),
(12,'São Paulo, GRU - Brasil','Belo Horizonte, CNF - Brasil'),
(13,'São Paulo, GRU - Brasil','Belém, BEL - Brasil'),
(14,'São Paulo, GRU - Brasil','João Pessoa, JPA - Brasil'),
(15,'São Paulo, GRU - Brasil','Curitiba, CWB - Brasil'),
(16,'São Paulo, GRU - Brasil','Recife, REC - Brasil'),
(17,'São Paulo, GRU - Brasil','Teresina, THE - Brasil'),
(18,'São Paulo, GRU - Brasil','Rio de Janeiro, SDU - Brasil'),
(19,'São Paulo, GRU - Brasil','Natal, NAT - Brasil'),
(20,'São Paulo, GRU - Brasil','Porto Alegre, POA - Brasil'),
(21,'São Paulo, GRU - Brasil','Florianópolis, FLN - Brasil'),
(22,'São Paulo, GRU - Brasil','Aracaju, AJU - Brasil'),
(23,'São Paulo, GRU - Brasil','Palmas, PMW - Brasil');
