INSERT INTO `voo` VALUES 
(1,'São Paulo, GRU - Brasil','Rio Branco, RBR - Brasil','RBR'),
(2,'São Paulo, GRU - Brasil','Maceió, MCZ - Brasil','MCZ'),
(3,'São Paulo, GRU - Brasil','Manaus, MAO - Brasil','MAO'),
(4,'São Paulo, GRU - Brasil','Salvador da Bahia, SSA - Brasil','SSA'),
(5,'São Paulo, GRU - Brasil','Fortaleza, FOR - Brasil','FOR'),
(6,'São Paulo, GRU - Brasil','Brasília, BSB - Brasil','BSB'),
(7,'São Paulo, GRU - Brasil','Vitória, VIX - Brasil','VIX'),
(8,'São Paulo, GRU - Brasil','Goiânia, GYN - Brasil','GYN'),
(9,'São Paulo, GRU - Brasil','São Luís, SLZ - Brasil','SLZ'),
(10,'São Paulo, GRU - Brasil','Cuiabá, CGB - Brasil','CGB'),
(11,'São Paulo, GRU - Brasil','Campo Grande, CGR - Brasil','CGR'),
(12,'São Paulo, GRU - Brasil','Belo Horizonte, CNF - Brasil','CNF'),
(13,'São Paulo, GRU - Brasil','Belém, BEL - Brasil','BEL'),
(14,'São Paulo, GRU - Brasil','João Pessoa, JPA - Brasil','JPA'),
(15,'São Paulo, GRU - Brasil','Curitiba, CWB - Brasil','CWB'),
(16,'São Paulo, GRU - Brasil','Recife, REC - Brasil','REC'),
(17,'São Paulo, GRU - Brasil','Teresina, THE - Brasil','THE'),
(18,'São Paulo, GRU - Brasil','Rio de Janeiro, SDU - Brasil','SDU'),
(19,'São Paulo, GRU - Brasil','Natal, NAT - Brasil','NAT'),
(20,'São Paulo, GRU - Brasil','Porto Alegre, POA - Brasil','POA'),
(21,'São Paulo, GRU - Brasil','Florianópolis, FLN - Brasil','FLN'),
(22,'São Paulo, GRU - Brasil','Aracaju, AJU - Brasil','AJU'),
(23,'São Paulo, GRU - Brasil','Palmas, PMW - Brasil','PMW');
